include $(MEMENTOS_ROOT)/Makefile.flags

override SRC_ROOT = ../../src

LIB = libdino

OBJECTS = \
	dino.o \

CFLAGS += \
	-I$(SRC_ROOT)/include \

DEPS += libmementos
DEP_ROOT_libmementos ?= $(MEMENTOS_ROOT)
